version: '2'
services:
  wildfly:
    build: ../images/wildfly
    links:
      - mysql:db
    ports:
     - "9090:8080"
     - "9990:9990"
  mysql: 
    build: ../images/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - "3306:3306"
  
  phpmyadmin:
    build: ../images/phpmyadmin
    links:
      - mysql:db
    ports:
      - "6060:80"
    environment:
      - MYSQL_ROOT_PASSWORD=admin